### ISSUE TITLE
unable to set up conda environment -- ImportError: libboost_system.so.1.57.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by porphyrius** [Juanlu001/fenics-recipes#58]
Dear Juanlu001,

I am sorry to bother you again, but every time I install a new Ubuntu system (now 15.10) I incur in troubles with setting up fenics in existing conda installations. I tried to follow your previous suggestions, but with no avail. I am testing my installation by running a program 'brwalk.py' which makes calls to dolfin, scipy, matplotlib. The feeling is that there is a problem with incompatible versions, but I cannot debug the problem. I am posting here my tentatives in the hope that you can get a hint from them at what is going wrong. 

```
andrea@brahma:~/Desktop/ArhGAP15/simulazione.2/1000$ conda create -n fenics27 python=2.7  

Fetching package metadata: ......
Solving package specifications: .........

Package plan for installation in environment /home/andrea/anaconda2/envs/fenics27:

The following NEW packages will be INSTALLED:

    openssl:    1.0.2g-0     
    pip:        8.1.1-py27_1 
    python:     2.7.11-0     
    readline:   6.2-2        
    setuptools: 20.7.0-py27_0
    sqlite:     3.9.2-0      
    tk:         8.5.18-0     
    wheel:      0.29.0-py27_0
    zlib:       1.2.8-0      

Proceed ([y]/n)? y

Linking packages ...
[      COMPLETE      ]|###################################################| 100%

andrea@brahma:~/Desktop/ArhGAP15/simulazione.2/1000$ source activate fenics27 

discarding /home/andrea/anaconda2/bin from PATH
prepending /home/andrea/anaconda2/envs/fenics27/bin to PATH
(fenics27)andrea@brahma:~/Desktop/ArhGAP15/simulazione.2/1000$ conda install fenics mkl --channel juanlu001 
Fetching package metadata: ........
Solving package specifications: .........

Package plan for installation in environment /home/andrea/anaconda2/envs/fenics27:

The following NEW packages will be INSTALLED:

    boost:       1.60.0-py27_0   
    cloog:       0.18.0-0        
    cmake:       3.3.1-0         
    dolfin:      1.6.0-py27_2    
    eigen3:      3.2.1-1         
    fenics:      1.6.0-0         
    ffc:         1.6.0-py27_3    
    fiat:        1.6.0-np19py27_1
    fontconfig:  2.11.1-5        
    freetype:    2.5.5-0         
    gcc:         4.8.5-3         
    gmp:         5.1.2-2         
    icu:         54.1-0          
    instant:     1.6.0-py27_3    
    isl:         0.12.2-0        
    libgcc:      4.8.5-1         
    libgfortran: 3.0-0           
    libpng:      1.6.17-0        
    libxml2:     2.9.2-0         
    mkl:         11.3.1-0        
    mpc:         1.0.1-0         
    mpfr:        3.1.2-0         
    mpi4py:      2.0.0-py27_1    
    mpich2:      1.4.1p1-0       
    mpmath:      0.19-py27_0     
    numpy:       1.9.3-py27_2    
    pcre:        8.31-0          
    petsc:       3.5.2-py27_2    
    petsc4py:    3.5.1-py27_1    
    ply:         3.8-py27_0      
    qt:          4.8.7-1         
    six:         1.10.0-py27_0   
    slepc:       3.5.4-py27_2    
    swig:        3.0.7-0         
    sympy:       1.0-py27_0      
    ufl:         1.6.0-py27_1    
    vtk:         6.3.0-py27_1    

Proceed ([y]/n)? y

Linking packages ...
[      COMPLETE      ]|###################################################| 100%

(fenics27)andrea@brahma:~/Desktop/ArhGAP15/simulazione.2/1000$ python brwalk.py

Traceback (most recent call last):
  File "brwalk.py", line 30, in <module>
    from scipy import *
ImportError: No module named scipy

(fenics27)andrea@brahma:~/Desktop/ArhGAP15/simulazione.2/1000$ conda install scipy --channel juanlu001 

Fetching package metadata: ........
Solving package specifications: .........

Package plan for installation in environment /home/andrea/anaconda2/envs/fenics27:

The following NEW packages will be INSTALLED:

    scipy: 0.17.0-np19py27_2

Proceed ([y]/n)? y

Linking packages ...
[      COMPLETE      ]|###################################################| 100%

(fenics27)andrea@brahma:~/Desktop/ArhGAP15/simulazione.2/1000$ python brwalk.py

Traceback (most recent call last):
  File "brwalk.py", line 31, in <module>
    from pylab import *
ImportError: No module named pylab

(fenics27)andrea@brahma:~/Desktop/ArhGAP15/simulazione.2/1000$ conda install matplotlib --channel juanlu001 

Fetching package metadata: ........
Solving package specifications: .........

Package plan for installation in environment /home/andrea/anaconda2/envs/fenics27:

The following NEW packages will be INSTALLED:

    cairo:           1.12.18-6       
    matplotlib:      1.4.3-np19py27_2
    pixman:          0.32.6-0        
    py2cairo:        1.10.0-py27_2   
    pyparsing:       2.0.3-py27_0    
    pyqt:            4.11.4-py27_1   
    python-dateutil: 2.5.2-py27_0    
    pytz:            2016.3-py27_0   
    sip:             4.16.9-py27_0   

Proceed ([y]/n)? y

Linking packages ...
[      COMPLETE      ]|###################################################| 100%

(fenics27)andrea@brahma:~/Desktop/ArhGAP15/simulazione.2/1000$ python brwalk.py

Traceback (most recent call last):
  File "brwalk.py", line 968, in <module>
    chemo1()
  File "brwalk.py", line 205, in chemo1
    from dolfin import Constant,Expression,Function,FunctionSpace,LUSolver,MeshFunction,Point,SubDomain,TestFunction,TrialFunction,VectorFunctionSpace             #  Solution of PDE
  File "/home/andrea/anaconda2/envs/fenics27/lib/python2.7/site-packages/dolfin/__init__.py", line 16, in <module>
    from . import cpp
  File "/home/andrea/anaconda2/envs/fenics27/lib/python2.7/site-packages/dolfin/cpp/__init__.py", line 42, in <module>
    exec("from . import %s" % module_name)
  File "<string>", line 1, in <module>
  File "/home/andrea/anaconda2/envs/fenics27/lib/python2.7/site-packages/dolfin/cpp/common.py", line 32, in <module>
    _common = swig_import_helper()
  File "/home/andrea/anaconda2/envs/fenics27/lib/python2.7/site-packages/dolfin/cpp/common.py", line 28, in swig_import_helper
    _mod = imp.load_module('_common', fp, pathname, description)
ImportError: libboost_system.so.1.57.0: cannot open shared object file: No such file or directory

(fenics27)andrea@brahma:~/Desktop/ArhGAP15/simulazione.2/1000$ conda install boost --channel juanlu001 

Fetching package metadata: ........
Solving package specifications: .........

All requested packages already installed.
packages in environment at /home/andrea/anaconda2/envs/fenics27:

boost                     1.60.0                   py27_0  

(fenics27)andrea@brahma:~/Desktop/ArhGAP15/simulazione.2/1000$ python brwalk.py

Traceback (most recent call last):
  File "brwalk.py", line 968, in <module>
    chemo1()
  File "brwalk.py", line 205, in chemo1
    from dolfin import Constant,Expression,Function,FunctionSpace,LUSolver,MeshFunction,Point,SubDomain,TestFunction,TrialFunction,VectorFunctionSpace             #  Solution of PDE
  File "/home/andrea/anaconda2/envs/fenics27/lib/python2.7/site-packages/dolfin/__init__.py", line 16, in <module>
    from . import cpp
  File "/home/andrea/anaconda2/envs/fenics27/lib/python2.7/site-packages/dolfin/cpp/__init__.py", line 42, in <module>
    exec("from . import %s" % module_name)
  File "<string>", line 1, in <module>
  File "/home/andrea/anaconda2/envs/fenics27/lib/python2.7/site-packages/dolfin/cpp/common.py", line 32, in <module>
    _common = swig_import_helper()
  File "/home/andrea/anaconda2/envs/fenics27/lib/python2.7/site-packages/dolfin/cpp/common.py", line 28, in swig_import_helper
    _mod = imp.load_module('_common', fp, pathname, description)
ImportError: libboost_system.so.1.57.0: cannot open shared object file: No such file or directory

(fenics27)andrea@brahma:~/Desktop/ArhGAP15/simulazione.2/1000$ conda install numpy=1.10.4 --channel juanlu001 

Fetching package metadata: ........
Solving package specifications: ....

The following specifications were found to be in conflict:
  - dolfin (target=dolfin-1.6.0-py27_2.tar.bz2) -> ffc ==1.6.0
  - fenics (target=fenics-1.6.0-0.tar.bz2) -> dolfin ==1.6.0
  - fenics (target=fenics-1.6.0-0.tar.bz2) -> ffc ==1.6.0
  - fenics (target=fenics-1.6.0-0.tar.bz2) -> fiat ==1.6.0
  - ffc (target=ffc-1.6.0-py27_3.tar.bz2)
  - fiat (target=fiat-1.6.0-np19py27_1.tar.bz2)
  - numpy 1.10.4*
Use "conda info <package>" to see the dependencies for each package.

(fenics27)andrea@brahma:~/Desktop/ArhGAP15/simulazione.2/1000$ conda remove dolfin fenics ffc fiat

Fetching package metadata: ......
Solving package specifications: .........

Package plan for package removal in environment /home/andrea/anaconda2/envs/fenics27:

The following packages will be REMOVED:

    dolfin: 1.6.0-py27_2    
    fenics: 1.6.0-0         
    ffc:    1.6.0-py27_3    
    fiat:   1.6.0-np19py27_1

Proceed ([y]/n)? y

Unlinking packages ...
[      COMPLETE      ]|###################################################| 100%

(fenics27)andrea@brahma:~/Desktop/ArhGAP15/simulazione.2/1000$ conda install numpy=1.10.4 --channel juanlu001 

Fetching package metadata: ........
Solving package specifications: .........

Package plan for installation in environment /home/andrea/anaconda2/envs/fenics27:

The following packages will be UPDATED:

    matplotlib: 1.4.3-np19py27_2  --> 1.4.3-np110py27_2 
    numpy:      1.9.3-py27_2      --> 1.10.4-py27_1     
    scipy:      0.17.0-np19py27_2 --> 0.17.0-np110py27_2

Proceed ([y]/n)? y

Unlinking packages ...
[      COMPLETE      ]|###################################################| 100%
Linking packages ...
[      COMPLETE      ]|###################################################| 100%

(fenics27)andrea@brahma:~/Desktop/ArhGAP15/simulazione.2/1000$ conda install fenics mkl --channel juanlu001

Fetching package metadata: ........
Solving package specifications: .........

Package plan for installation in environment /home/andrea/anaconda2/envs/fenics27:

The following NEW packages will be INSTALLED:

    dolfin:     1.6.0-py27_2     
    fenics:     1.6.0-0          
    ffc:        1.6.0-py27_3     
    fiat:       1.6.0-np19py27_1 

The following packages will be UPDATED:

    matplotlib: 1.4.3-np110py27_2  --> 1.4.3-np19py27_2 
    scipy:      0.17.0-np110py27_2 --> 0.17.0-np19py27_2

The following packages will be DOWNGRADED:

    numpy:      1.10.4-py27_1      --> 1.9.3-py27_2     

Proceed ([y]/n)? y

Unlinking packages ...
[      COMPLETE      ]|###################################################| 100%
Linking packages ...
[      COMPLETE      ]|###################################################| 100%

(fenics27)andrea@brahma:~/Desktop/ArhGAP15/simulazione.2/1000$ python brwalk.py

Traceback (most recent call last):
  File "brwalk.py", line 968, in <module>
    chemo1()
  File "brwalk.py", line 205, in chemo1
    from dolfin import Constant,Expression,Function,FunctionSpace,LUSolver,MeshFunction,Point,SubDomain,TestFunction,TrialFunction,VectorFunctionSpace             #  Solution of PDE
  File "/home/andrea/anaconda2/envs/fenics27/lib/python2.7/site-packages/dolfin/__init__.py", line 16, in <module>
    from . import cpp
  File "/home/andrea/anaconda2/envs/fenics27/lib/python2.7/site-packages/dolfin/cpp/__init__.py", line 42, in <module>
    exec("from . import %s" % module_name)
  File "<string>", line 1, in <module>
  File "/home/andrea/anaconda2/envs/fenics27/lib/python2.7/site-packages/dolfin/cpp/common.py", line 32, in <module>
    _common = swig_import_helper()
  File "/home/andrea/anaconda2/envs/fenics27/lib/python2.7/site-packages/dolfin/cpp/common.py", line 28, in swig_import_helper
    _mod = imp.load_module('_common', fp, pathname, description)
ImportError: libboost_system.so.1.57.0: cannot open shared object file: No such file or directory
```

**Comment by GaZ3ll3** [comment]
@porphyrius 

you installed boost 1.60

see your first a few lines:  `boost:       1.60.0-py27_0`

lower the version of boost

`conda install boost=1.57`

and also the version of vtk

`conda install vtk=5.10`

also, very important, the mkl.

`conda install mkl=11.1` 

I don't why 11.3.1 could not work, but it seems you can only have trial mode for 30 days.........

**Comment by astrojuanlu** [comment]
Thanks @GaZ3ll3 for this late answer. Please @porphyrius confirm if this can be closed, boost is a mess and I should take the time to pin the version once and for all...

@GaZ3ll3 what do you mean that 11.3.1 won't work? In principle the new recipes should not depend on MKL but I would have to check to be sure.

**Comment by GaZ3ll3** [comment]
@Juanlu001 continuum team seems get another way of installation of mkl, they removes mkl-service and mkl-rt, and only use mkl in current version (point out if I am wrong, I cannot find their thread on this problem in their issue, but it is about some numpy+mkl...). If your recipe does not depend on mkl, you probably should add `nomkl` as dependency, it will remove all `mkl` features, which means `numpy` and those stuff using `mkl` will change to none-mkl version.

**Comment by astrojuanlu** [comment]
Thanks for the clarifications, I will have to consider it if I have some time to work on this and other pending issues.

**Comment by porphyrius** [comment]
Hi https://github.com/Juanlu001 and https://github.com/GaZ3ll3, thanks a lot for your help.
So I wiped out my fenics27 environment and started everything anew trying to follow your suggestions.
But still no luck:

```
andrea@brahma:~/Desktop/ArhGAP15/simulazione.2/1000$ conda remove --name fenics27 --all
Fetching package metadata: ......

Package plan for package removal in environment /home/andrea/anaconda2/envs/fenics27:

The following packages will be REMOVED:

    backports:         1.0-py27_0       
    boost:             1.57.0-4         
    cmake:             3.3.1-0          
    decorator:         4.0.9-py27_0     
    dolfin:            1.5.0-np19py27_2 
    eigen3:            3.2.1-1          
    fenics:            1.5.0-0          
    ffc:               1.5.0-np19py27_2 
    fiat:              1.5.0-np19py27_1 
    fontconfig:        2.11.1-5         
    freetype:          2.5.5-0          
    get_terminal_size: 1.0.0-py27_0     
    icu:               54.1-0           
    instant:           1.5.0-np19py27_1 
    ipython:           4.2.0-py27_0     
    ipython_genutils:  0.1.0-py27_0     
    libgcc:            5.2.0-0          
    libgfortran:       3.0-0            
    libpng:            1.6.17-0         
    libxml2:           2.9.2-0          
    mkl:               11.3.1-0         
    mkl-rt:            11.1-p0          
    mkl-service:       1.0.0-py27_p2    
    mpi4py:            2.0.0-py27_1     
    mpich2:            1.4.1p1-0        
    mpmath:            0.19-py27_0      
    nose:              1.3.7-py27_0     
    numexpr:           2.3.1-np19py27_0 
    numpy:             1.9.1-py27_0     
    openblas:          0.2.14-4         
    openssl:           1.0.2g-0         
    path.py:           8.2.1-py27_0     
    pcre:              8.31-0           
    petsc:             3.5.2-py27_2     
    petsc4py:          3.5.1-py27_1     
    pexpect:           4.0.1-py27_0     
    pickleshare:       0.5-py27_0       
    pip:               8.1.1-py27_1     
    ply:               3.8-py27_0       
    ptyprocess:        0.5-py27_0       
    python:            2.7.11-0         
    qt:                4.8.7-1          
    readline:          6.2-2            
    scikit-learn:      0.15.2-np19py27_0
    scipy:             0.17.0-np19py27_2
    setuptools:        20.7.0-py27_0    
    simplegeneric:     0.8.1-py27_0     
    six:               1.10.0-py27_0    
    slepc:             3.5.4-py27_2     
    sqlite:            3.9.2-0          
    swig:              3.0.8-1          
    sympy:             1.0-py27_0       
    tk:                8.5.18-0         
    traitlets:         4.2.1-py27_0     
    ufl:               1.5.0-py27_1     
    vtk:               5.10.1-py27_1    
    wheel:             0.29.0-py27_0    
    zlib:              1.2.8-0          

Proceed ([y]/n)? y

Unlinking packages ...
[      COMPLETE      ]|###################################################| 100%
andrea@brahma:~/Desktop/ArhGAP15/simulazione.2/1000$ conda create -n fenics27 python=2.7
Fetching package metadata: ......
Solving package specifications: .........

Package plan for installation in environment /home/andrea/anaconda2/envs/fenics27:

The following NEW packages will be INSTALLED:

    openssl:    1.0.2g-0     
    pip:        8.1.1-py27_1 
    python:     2.7.11-0     
    readline:   6.2-2        
    setuptools: 20.7.0-py27_0
    sqlite:     3.9.2-0      
    tk:         8.5.18-0     
    wheel:      0.29.0-py27_0
    zlib:       1.2.8-0      

Proceed ([y]/n)? y

Linking packages ...
[      COMPLETE      ]|###################################################| 100%
andrea@brahma:~/Desktop/ArhGAP15/simulazione.2/1000$ source activate fenics27
discarding /home/andrea/anaconda2/bin from PATH
prepending /home/andrea/anaconda2/envs/fenics27/bin to PATH
(fenics27)andrea@brahma:~/Desktop/ArhGAP15/simulazione.2/1000$ conda install numpy=1.9.1
Fetching package metadata: ......
Solving package specifications: .........

Package plan for installation in environment /home/andrea/anaconda2/envs/fenics27:

The following NEW packages will be INSTALLED:

    numpy: 1.9.1-py27_0

Proceed ([y]/n)? y

Linking packages ...
[      COMPLETE      ]|###################################################| 100%
(fenics27)andrea@brahma:~/Desktop/ArhGAP15/simulazione.2/1000$ conda install boost=1.57
Fetching package metadata: ......
Solving package specifications: .........

Package plan for installation in environment /home/andrea/anaconda2/envs/fenics27:

The following NEW packages will be INSTALLED:

    boost: 1.57.0-4
    icu:   54.1-0  

Proceed ([y]/n)? y

Linking packages ...
[      COMPLETE      ]|###################################################| 100%
(fenics27)andrea@brahma:~/Desktop/ArhGAP15/simulazione.2/1000$ conda install vtk=5.10
Fetching package metadata: ......
Solving package specifications: .........

Package plan for installation in environment /home/andrea/anaconda2/envs/fenics27:

The following NEW packages will be INSTALLED:

    vtk: 5.10.1-py27_1

Proceed ([y]/n)? y

Linking packages ...
[      COMPLETE      ]|###################################################| 100%
(fenics27)andrea@brahma:~/Desktop/ArhGAP15/simulazione.2/1000$ conda install mkl=11.1
Fetching package metadata: ......
Solving package specifications: .........

Package plan for installation in environment /home/andrea/anaconda2/envs/fenics27:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    numpy-1.9.1                |          py27_p0         5.7 MB

The following NEW packages will be INSTALLED:

    mkl:          11.1-np19py27_p3  
    mkl-rt:       11.1-p0           
    mkl-service:  1.0.0-py27_p2     
    nose:         1.3.7-py27_0      
    numexpr:      2.3.1-np19py27_p0  [mkl]
    scikit-learn: 0.15.2-np19py27_p0 [mkl]
    scipy:        0.16.1-np19py27_p0 [mkl]

The following packages will be UPDATED:

    numpy:        1.9.1-py27_0 --> 1.9.1-py27_p0      [mkl]

Proceed ([y]/n)? y

Fetching packages ...
numpy-1.9.1-py 100% |################################| Time: 0:00:02   2.04 MB/s
Extracting packages ...
[      COMPLETE      ]|###################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|###################################################| 100%
Linking packages ...
[      COMPLETE      ]|###################################################| 100%
(fenics27)andrea@brahma:~/Desktop/ArhGAP15/simulazione.2/1000$ conda install fenics=1.5.0 --channel juanlu001
Fetching package metadata: ........
Solving package specifications: .........

Package plan for installation in environment /home/andrea/anaconda2/envs/fenics27:

The following NEW packages will be INSTALLED:

    cmake:        3.3.1-0          
    dolfin:       1.5.0-np19py27_2 
    eigen3:       3.2.1-1          
    fenics:       1.5.0-0          
    ffc:          1.5.0-np19py27_2 
    fiat:         1.5.0-np19py27_1 
    fontconfig:   2.11.1-5         
    freetype:     2.5.5-0          
    instant:      1.5.0-np19py27_1 
    libgcc:       5.2.0-0          
    libgfortran:  3.0-0            
    libpng:       1.6.17-0         
    libxml2:      2.9.2-0          
    mpi4py:       2.0.0-py27_1     
    mpich2:       1.4.1p1-0        
    mpmath:       0.19-py27_0      
    pcre:         8.31-0           
    petsc:        3.5.2-py27_2     
    petsc4py:     3.5.1-py27_1     
    ply:          3.8-py27_0       
    qt:           4.8.7-1          
    six:          1.10.0-py27_0    
    slepc:        3.5.4-py27_2     
    swig:         3.0.8-1          
    sympy:        1.0-py27_0       
    ufl:          1.5.0-py27_1     

The following packages will be UPDATED:

    mkl:          11.1-np19py27_p3   --> 11.3.1-0         
    numexpr:      2.3.1-np19py27_p0  [mkl] --> 2.3.1-np19py27_0 
    numpy:        1.9.1-py27_p0      [mkl] --> 1.9.1-py27_0     
    scikit-learn: 0.15.2-np19py27_p0 [mkl] --> 0.15.2-np19py27_0
    scipy:        0.16.1-np19py27_p0 [mkl] --> 0.17.0-np19py27_2

Proceed ([y]/n)? y

Unlinking packages ...
[      COMPLETE      ]|###################################################| 100%
Linking packages ...
[      COMPLETE      ]|###################################################| 100%
(fenics27)andrea@brahma:~/Desktop/ArhGAP15/simulazione.2/1000$ conda install mkl=11.1
Fetching package metadata: ......
Solving package specifications: .........

Package plan for installation in environment /home/andrea/anaconda2/envs/fenics27:

The following packages will be UPDATED:

    numexpr:      2.3.1-np19py27_0  --> 2.3.1-np19py27_p0  [mkl]
    numpy:        1.9.1-py27_0      --> 1.9.1-py27_p0      [mkl]
    scikit-learn: 0.15.2-np19py27_0 --> 0.15.2-np19py27_p0 [mkl]

The following packages will be DOWNGRADED:

    mkl:          11.3.1-0          --> 11.1-np19py27_p3  
    scipy:        0.17.0-np19py27_2 --> 0.16.1-np19py27_p0 [mkl]

Proceed ([y]/n)? y

Unlinking packages ...
[      COMPLETE      ]|###################################################| 100%
Linking packages ...
[      COMPLETE      ]|###################################################| 100%
(fenics27)andrea@brahma:~/Desktop/ArhGAP15/simulazione.2/1000$ conda install ipython
Fetching package metadata: ......
Solving package specifications: .........

Package plan for installation in environment /home/andrea/anaconda2/envs/fenics27:

The following NEW packages will be INSTALLED:

    backports:         1.0-py27_0       
    decorator:         4.0.9-py27_0     
    get_terminal_size: 1.0.0-py27_0     
    ipython:           4.2.0-py27_0     
    ipython_genutils:  0.1.0-py27_0     
    path.py:           8.2.1-py27_0     
    pexpect:           4.0.1-py27_0     
    pickleshare:       0.5-py27_0       
    ptyprocess:        0.5-py27_0       
    simplegeneric:     0.8.1-py27_0     
    traitlets:         4.2.1-py27_0     

The following packages will be UPDATED:

    mkl:               11.1-np19py27_p3   --> 11.3.1-0         
    numexpr:           2.3.1-np19py27_p0  [mkl] --> 2.3.1-np19py27_0 
    numpy:             1.9.1-py27_p0      [mkl] --> 1.9.1-py27_0     
    scikit-learn:      0.15.2-np19py27_p0 [mkl] --> 0.15.2-np19py27_0
    scipy:             0.16.1-np19py27_p0 [mkl] --> 0.17.0-np19py27_2

Proceed ([y]/n)? y

Unlinking packages ...
[      COMPLETE      ]|###################################################| 100%
Linking packages ...
[      COMPLETE      ]|###################################################| 100%
(fenics27)andrea@brahma:~/Desktop/ArhGAP15/simulazione.2/1000$ conda install mkl=11.1
Fetching package metadata: ......
Solving package specifications: .........

Package plan for installation in environment /home/andrea/anaconda2/envs/fenics27:

The following packages will be UPDATED:

    numexpr:      2.3.1-np19py27_0  --> 2.3.1-np19py27_p0  [mkl]
    numpy:        1.9.1-py27_0      --> 1.9.1-py27_p0      [mkl]
    scikit-learn: 0.15.2-np19py27_0 --> 0.15.2-np19py27_p0 [mkl]

The following packages will be DOWNGRADED:

    mkl:          11.3.1-0          --> 11.1-np19py27_p3  
    scipy:        0.17.0-np19py27_2 --> 0.16.1-np19py27_p0 [mkl]

Proceed ([y]/n)? y

Unlinking packages ...
[      COMPLETE      ]|###################################################| 100%
Linking packages ...
[      COMPLETE      ]|###################################################| 100%
(fenics27)andrea@brahma:~/Desktop/ArhGAP15/simulazione.2/1000$ ipython
Python 2.7.11 |Continuum Analytics, Inc.| (default, Dec  6 2015, 18:08:32) 
Type "copyright", "credits" or "license" for more information.

IPython 4.2.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: %run -i brwalk.py
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/home/andrea/lavoro/ArhGAP15/simulazione.2/1000/brwalk.py in <module>()
     28 from time import sleep
     29 from timeit import timeit
---> 30 from scipy import *
     31 from pylab import *
     32 from scipy.ndimage import label

/home/andrea/anaconda2/envs/fenics27/lib/python2.7/site-packages/scipy/__init__.py in <module>()
     59 __all__ = ['test']
     60 
---> 61 from numpy import show_config as show_numpy_config
     62 if show_numpy_config is None:
     63     raise ImportError("Cannot import scipy when running from numpy source directory.")

/home/andrea/anaconda2/envs/fenics27/lib/python2.7/site-packages/numpy/__init__.pyc in <module>()
    170         return loader(*packages, **options)
    171 
--> 172     from . import add_newdocs
    173     __all__ = ['add_newdocs',
    174                'ModuleDeprecationWarning',

/home/andrea/anaconda2/envs/fenics27/lib/python2.7/site-packages/numpy/add_newdocs.py in <module>()
     11 from __future__ import division, absolute_import, print_function
     12 
---> 13 from numpy.lib import add_newdoc
     14 
     15 ###############################################################################

/home/andrea/anaconda2/envs/fenics27/lib/python2.7/site-packages/numpy/lib/__init__.py in <module>()
     16 
     17 from . import scimath as emath
---> 18 from .polynomial import *
     19 #import convertcode
     20 from .utils import *

/home/andrea/anaconda2/envs/fenics27/lib/python2.7/site-packages/numpy/lib/polynomial.py in <module>()
     17 from numpy.lib.function_base import trim_zeros, sort_complex
     18 from numpy.lib.type_check import iscomplex, real, imag
---> 19 from numpy.linalg import eigvals, lstsq, inv
     20 
     21 class RankWarning(UserWarning):

/home/andrea/anaconda2/envs/fenics27/lib/python2.7/site-packages/numpy/linalg/__init__.py in <module>()
     49 from .info import __doc__
     50 
---> 51 from .linalg import *
     52 
     53 from numpy.testing import Tester

/home/andrea/anaconda2/envs/fenics27/lib/python2.7/site-packages/numpy/linalg/linalg.py in <module>()
     27     )
     28 from numpy.lib import triu, asfarray
---> 29 from numpy.linalg import lapack_lite, _umath_linalg
     30 from numpy.matrixlib.defmatrix import matrix_power
     31 from numpy.compat import asbytes

ImportError: libmkl_intel_lp64.so: cannot open shared object file: No such file or directory

In [2]: 
Do you really want to exit ([y]/n)? y
(fenics27)andrea@brahma:~/Desktop/ArhGAP15/simulazione.2/1000$ conda install scipy
Fetching package metadata: ......
Solving package specifications: .........

Package plan for installation in environment /home/andrea/anaconda2/envs/fenics27:

The following packages will be UPDATED:

    mkl:          11.1-np19py27_p3   --> 11.3.1-0         
    numexpr:      2.3.1-np19py27_p0  [mkl] --> 2.3.1-np19py27_0 
    numpy:        1.9.1-py27_p0      [mkl] --> 1.9.1-py27_0     
    scikit-learn: 0.15.2-np19py27_p0 [mkl] --> 0.15.2-np19py27_0
    scipy:        0.16.1-np19py27_p0 [mkl] --> 0.17.0-np19py27_2

Proceed ([y]/n)? y

Unlinking packages ...
[      COMPLETE      ]|###################################################| 100%
Linking packages ...
[      COMPLETE      ]|###################################################| 100%
(fenics27)andrea@brahma:~/Desktop/ArhGAP15/simulazione.2/1000$ conda install mkl=11.1
Fetching package metadata: ......
Solving package specifications: .........

Package plan for installation in environment /home/andrea/anaconda2/envs/fenics27:

The following packages will be UPDATED:

    numexpr:      2.3.1-np19py27_0  --> 2.3.1-np19py27_p0  [mkl]
    numpy:        1.9.1-py27_0      --> 1.9.1-py27_p0      [mkl]
    scikit-learn: 0.15.2-np19py27_0 --> 0.15.2-np19py27_p0 [mkl]

The following packages will be DOWNGRADED:

    mkl:          11.3.1-0          --> 11.1-np19py27_p3  
    scipy:        0.17.0-np19py27_2 --> 0.16.1-np19py27_p0 [mkl]

Proceed ([y]/n)? y

Unlinking packages ...
[      COMPLETE      ]|###################################################| 100%
Linking packages ...
[      COMPLETE      ]|###################################################| 100%
(fenics27)andrea@brahma:~/Desktop/ArhGAP15/simulazione.2/1000$ ipython
Python 2.7.11 |Continuum Analytics, Inc.| (default, Dec  6 2015, 18:08:32) 
Type "copyright", "credits" or "license" for more information.

IPython 4.2.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: %run -i brwalk.py
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/home/andrea/lavoro/ArhGAP15/simulazione.2/1000/brwalk.py in <module>()
     28 from time import sleep
     29 from timeit import timeit
---> 30 from scipy import *
     31 from pylab import *
     32 from scipy.ndimage import label

/home/andrea/anaconda2/envs/fenics27/lib/python2.7/site-packages/scipy/__init__.py in <module>()
     59 __all__ = ['test']
     60 
---> 61 from numpy import show_config as show_numpy_config
     62 if show_numpy_config is None:
     63     raise ImportError("Cannot import scipy when running from numpy source directory.")

/home/andrea/anaconda2/envs/fenics27/lib/python2.7/site-packages/numpy/__init__.pyc in <module>()
    170         return loader(*packages, **options)
    171 
--> 172     from . import add_newdocs
    173     __all__ = ['add_newdocs',
    174                'ModuleDeprecationWarning',

/home/andrea/anaconda2/envs/fenics27/lib/python2.7/site-packages/numpy/add_newdocs.py in <module>()
     11 from __future__ import division, absolute_import, print_function
     12 
---> 13 from numpy.lib import add_newdoc
     14 
     15 ###############################################################################

/home/andrea/anaconda2/envs/fenics27/lib/python2.7/site-packages/numpy/lib/__init__.py in <module>()
     16 
     17 from . import scimath as emath
---> 18 from .polynomial import *
     19 #import convertcode
     20 from .utils import *

/home/andrea/anaconda2/envs/fenics27/lib/python2.7/site-packages/numpy/lib/polynomial.py in <module>()
     17 from numpy.lib.function_base import trim_zeros, sort_complex
     18 from numpy.lib.type_check import iscomplex, real, imag
---> 19 from numpy.linalg import eigvals, lstsq, inv
     20 
     21 class RankWarning(UserWarning):

/home/andrea/anaconda2/envs/fenics27/lib/python2.7/site-packages/numpy/linalg/__init__.py in <module>()
     49 from .info import __doc__
     50 
---> 51 from .linalg import *
     52 
     53 from numpy.testing import Tester

/home/andrea/anaconda2/envs/fenics27/lib/python2.7/site-packages/numpy/linalg/linalg.py in <module>()
     27     )
     28 from numpy.lib import triu, asfarray
---> 29 from numpy.linalg import lapack_lite, _umath_linalg
     30 from numpy.matrixlib.defmatrix import matrix_power
     31 from numpy.compat import asbytes

ImportError: libmkl_intel_lp64.so: cannot open shared object file: No such file or directory

In [2]: 
```

**Comment by astrojuanlu** [comment]
Well, as you can see this is a different breed of problem. Now everything's fine with boost, but the issue now is with Intel MKL, as @GaZ3ll3 anticipated. Please specify also the mkl version, as said [in a previous comment](https://github.com/Juanlu001/fenics-recipes/issues/58#issuecomment-214865069).

**Comment by porphyrius** [comment]
I did that:

   conda install mkl=11.1

Then it got upgraded automatically when installing some other program, and I downgraded it each time.

**Comment by astrojuanlu** [comment]
My fault, I didn't see that part. In fact there must be some nasty interaction between MKL and the switch to OpenBLAS:

https://github.com/Juanlu001/fenics-recipes/commit/f929f3a27e8137a6cd46da33bbb17e36f74c899b

I last touched these packages before Continuum made the latest significant changes to MKL distribution. I'm sorry but I won't have time to fix this in the short term, I encourage you to check the many forks of these recipes that are out there:

https://github.com/Juanlu001/fenics-recipes/network

In particular, the most advanced one is the one by @mikaem.

**Comment by GaZ3ll3** [comment]
@porphyrius @Juanlu001 checkout https://github.com/mikaem/fenics-recipes/blob/conda-gcc/build_fenics.sh in https://github.com/mikaem/fenics-recipes/tree/conda-gcc branch

I tried this installation from local, directly `bash build_fenics.sh`. It looks ok, but it is `1.7`.

in the comments, he mentioned a problem which I encountered multiple times. It is about the libgfortran. Hope it helps.
